create table if not exists api_usage_stats (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  model text not null,
  tokens int not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table api_usage_stats enable row level security;

create policy "Users can view their own usage"
  on api_usage_stats for select
  using (auth.uid() = user_id);

create index if not exists idx_api_usage_stats_user_id on api_usage_stats(user_id);